### ISSUE TITLE
Editor doesn't support I/O parameters using the FEEL format

### ISSUE THREAD

**Issue by Ryaryu** [zeebe-io/zeebe-modeler#231] opened 2020-05-27 12:11 UTC
Hello,

According to [this](https://docs.zeebe.io/reference/variables.html#inputoutput-variable-mappings) documentation, we should be using FEEL expressions in the source field of a input variable, but the editor doesn't allow such expressions in the source field:

![image](https://user-images.githubusercontent.com/6576943/83017188-96914f80-9ff9-11ea-9c84-a1b199cdcd02.png)

If you edit this manually, it is accepted by the Zeebe server. The problem is just this validation in the modeler.
I'm using the 0.9.1 version of the modeler.

**Comment by nikku** [comment] 2020-05-27 12:27
Related to / duplicate of https://github.com/zeebe-io/zeebe-modeler/issues/231.

**Comment by pinussilvestrus** [comment] 2020-08-05 09:36
Closed via https://github.com/zeebe-io/zeebe-modeler/pull/240

**Closed by pinussilvestrus** 2020-08-05 09:36 UTC
Labels: bug, needs review
