### ISSUE TITLE
unknown attribute <bounds> [ warning ]

### ISSUE THREAD

**Issue by cameronbraid** [zeebe-io/zeebe-modeler#254] opened 2020-09-17 16:01 UTC
version 0.9.1

Every now and again I get error `unknown attribute <bounds> [ warning ]`

Looks like the following xml

```
      <bpmndi:BPMNEdge id="Flow_0fvepvj_di" bpmnElement="Flow_0fvepvj" bounds="[object Object]">
        <di:waypoint x="1318" y="642" />
        <di:waypoint x="1447" y="642" />
      </bpmndi:BPMNEdge>

```

**Comment by pinussilvestrus** [comment] 2020-09-18 08:56
Hi! Can you maybe be a bit more specific and use our [bug report template](https://github.com/zeebe-io/zeebe-modeler/issues/new?labels=bug&template=BUG_REPORT.md)? It will help us to understand the problem and maybe reproduce it.

**Comment by pinussilvestrus** [comment] 2020-09-22 09:49
I'll close this due to incomplete information. Feel free to re-open once you can share more information about the problem.

**Closed by pinussilvestrus** 2020-09-22 09:49 UTC
Labels: bug, help wanted
