### ISSUE TITLE
The link under Help > Documentation leads to a 404 Error

### ISSUE THREAD

**Issue by vringar** [zeebe-io/zeebe-modeler#176] opened 2020-02-13 14:53 UTC
__Describe the Bug__

When clicking on the button mentioned in title, one gets send to https://docs.zeebe.io/bpmn-modeler/README.html which doesn't exist (anymore?).

__Expected Behavior__
 The button would open the actual page with documentation.

__Environment__

- OS: Linux
- Zeebe Modeler Version: 0.8.0 built from source

**Comment by pinussilvestrus** [comment] 2020-02-13 15:01
This is a duplicate of https://github.com/zeebe-io/zeebe-modeler/issues/168, and will be fixed with the upcoming release.

**Closed by pinussilvestrus** 2020-02-13 15:01 UTC
Labels: bug

**Comment by pinussilvestrus** [comment] 2020-02-13 15:04
I also updated the develop branch, so it will be available in the next [nightly build](https://zeebe-modeler-nightly.s3.eu-central-1.amazonaws.com/), cf. https://github.com/zeebe-io/zeebe-modeler/commit/e8ec318eff8798312ae4759dfa8f476aded2d011
