### ISSUE TITLE
Building the repo throws an error

### ISSUE THREAD

**Issue by younes-io** [zeebe-io/zeebe-modeler#294] opened 2021-04-02 09:14 UTC
__Describe the Bug__

```
> node tasks/distro.js


Building zeebe-modeler distro

---

  version: 0.11.0
  platforms: [current]
  publish: false

---

electron-builder -c.forceCodeSigning=false --publish=never -c.artifactName=${name}-${version}-${os}-${arch}.${ext} -c.dmg.artifactName=${name}-${version}-${os}.${ext} -c.nsis.artifactName=${name}-${version}-${os}-setup.${ext} -c.nsisWeb.artifactName=${name}-${version}-${os}-web-setup.${ext}

/mnt/c/dev/experiment/zeebe-modeler/node_modules/execa/index.js:347
                throw err;
                ^

Error: spawnSync electron-builder ENOENT
    at Object.spawnSync (internal/child_process.js:1002:20)
    at Object.spawnSync (child_process.js:614:24)
    at module.exports.sync (/mnt/c/dev/experiment/zeebe-modeler/node_modules/execa/index.js:334:30)
    at Object.<anonymous> (/mnt/c/dev/experiment/zeebe-modeler/tasks/distro.js:132:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeebe-modeler-builder@0.5.0 build:distro: `node tasks/distro.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeebe-modeler-builder@0.5.0 build:distro script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devme/.npm/_logs/2021-04-02T09_07_30_900Z-debug.log
ERROR: "build:distro --" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeebe-modeler-builder@0.5.0 build: `run-s client:build "build:distro -- {@}"  --`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeebe-modeler-builder@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devme/.npm/_logs/2021-04-02T09_07_30_957Z-debug.log
ERROR: "build --" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeebe-modeler-builder@0.5.0 all: `run-s clean   "build -- {@}" --`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeebe-modeler-builder@0.5.0 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devme/.npm/_logs/2021-04-02T09_07_31_004Z-debug.log
```

__Steps to Reproduce__

1. Run `npm install`
2. Run  `npm run all`

__Expected Behavior__

No error should be thrown.

__Environment__

 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.20 GB / 7.84 GB
  Binaries:
    Node: 12.18.3 
    npm: 6.14.9

**Comment by pinussilvestrus** [comment] 2021-04-06 07:56
The steps you described worked for me on macOS 10.15. 

Maybe it's a Windows-related problem, maybe @philippfromme can double-check.

**Comment by pinussilvestrus** [comment] 2021-04-07 12:10
I tried it out on a Windows machine and it also worked without problems. 
OS: Windows 10
Node: v14.15.5
npm: v6.14.11

Can you try to update your node installation and check whether it starts working?

**Comment by nikku** [comment] 2021-04-12 15:52
Closing this issue as we cannot reproduce it on our end. Happy to continue digging if you provide further details.

**Closed as completed by nikku** 2021-04-12 15:52 UTC
Labels: bug, help wanted
