### ISSUE TITLE
Error trying to deploy to Camunda Cloud: Cluster Id error with "Should point to a running Zeebe Cluster."

### ISSUE THREAD

**Issue by ceefour** [zeebe-io/zeebe-modeler#216] opened 2020-04-20 21:08 UTC
__Describe the Bug__

Error trying to deploy to Camunda Cloud (0.22): Cluster Id error with "Should point to a running Zeebe Cluster."

__Steps to Reproduce__

1. Open BPMN
2. Click Deploy
3. Choose Camunda Cloud
4. Set Cluster ID, Client and Secret

![image](https://user-images.githubusercontent.com/24123/79800932-68c84380-8387-11ea-8857-c1899f19c55f.png)

`zbctl deploy` (v0.23.alpha2) works.

__Expected Behavior__

No error, can click Deploy then deployed.

__Environment__

- OS: Ubuntu 18.04
- Zeebe Modeler Version: 0.9.0

**Comment by oguzeroglu** [comment] 2020-04-21 06:42
Hey,

It may take a while after you created your cluster in Camunda Cloud until it is visible in DNS records.

Could you verify if this problem still occurs in order to make sure if this is not a DNS caching issue?

**Comment by ceefour** [comment] 2020-04-21 06:58
My cluster has been running for more than a week.

And as I mentioned, I can `zbctl deploy` to the cluster successfully, many times. It's only Zeebe Modeler that is not working. I just checked again, and still same behavior.

Note probably related, that zbctl 0.22.2 is also not working with Camunda Cloud. I had to use zbctl 0.23.alpha2.

**Comment by nikku** [comment] 2020-04-21 07:19
I attempted to reproduce the issue and failed:

* Create a new Cluster 
* Create a new Client for the cluster
* Enter credentials / contact point information into Zeebe Modeler

__Deployment worked smoothly.__

**Comment by nikku** [comment] 2020-04-21 07:20
@oguzeroglu Is there some advanced logging we can enable? Would be interesting in which way the connection check fails.

**Comment by nikku** [comment] 2020-04-21 07:25
@ceefour Could you restart the Zeebe Modeler and see if the problem persists across app restart?

**Comment by ceefour** [comment] 2020-04-21 08:50
@nikku I tried it again after reopening Zeebe Modeler and it works now.

BTW, it was not strictly a network issue, because even when it "doesn't work", if I put a wrong Client ID or secret it correctly complain about authentication. So the authentication part is working well.

I'm closing this but I agree with @nikku that Zeebe Modeler should give a better error message than just "Should point to a running Zeebe Cluster". Especially as this is a tool for developers, showing the HTTP error code (503? 500? 401? cannot resolve DNS?) and even more detail is very much welcome. (will also help to avoid issues like this/reduce diagnostics effort in GitHub/forums)

**Comment by oguzeroglu** [comment] 2020-04-21 09:31
Thanks for the feedback @ceefour. I opened the issue #217 which will help us get the full logs in case of connection errors once we implement this.

**Comment by nikku** [comment] 2020-04-23 09:18
Reopening, as this apparently confuses a lot of users.

**Comment by nikku** [comment] 2020-04-23 09:33
Once addressed we should cut a patch release of the Zeebe Modeler with the fix/mitigation.

**Comment by barmac** [comment] 2020-04-23 09:34
All righty!

**Comment by barmac** [comment] 2020-04-29 12:28
I could not reproduce it after https://github.com/zeebe-io/zeebe-modeler/pull/222 was merged. I tested with Zeebe 0.22.2 and 0.23.1 clusters.

**Closed by barmac** 2020-04-29 12:28 UTC
Labels: bug, ready
